=== TenzingT-Lama2001/GaloreGifts/catalog_20049082.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!-- schema declaration -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="Contact" type="xs:string" />
    <xs:element name="Blog" type="xs:string" />
    <xs:element name="Pricing" type="xs:string" />
    <xs:element name="Shop" type="xs:string" />


    <xs:element name="ShopBtn" type="xs:string" />
    <xs:element name="Nav_Menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Shop" />
                <xs:element ref="Pricing" />
                <xs:element ref="Blog" />
                <xs:element ref="Contact" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Galore_Logo" type="xs:string" />

    <xs:element name="Nav">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Galore_Logo" />
                <xs:element ref="Nav_Menu" />
                <xs:element ref="ShopBtn" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="CallToActionBtn" type="xs:string" />
    <xs:element name="Info" type="xs:string" />

    <xs:element name="Sub_Title" type="xs:string" />
    <xs:element name="Title" type="xs:string" />

    <xs:element name="Description">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Title" />
                <xs:element ref="Sub_Title" />
                <xs:element ref="Info" />
                <xs:element ref="CallToActionBtn" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="Photo" type="xs:string" />


    <xs:element name="Body">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Description" />
                <xs:element ref="Photo" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="Home">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Nav" />
                <xs:element ref="Body" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="label" type="xs:string" />


    <xs:element name="Terms_Condition" type="xs:string" />


    <xs:element name="Guideline" type="xs:string" />

    <xs:element name="Guide">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label" />
                <xs:element ref="Guideline" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Return">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Within 7 days" />
                <xs:enumeration value="Not Available" />
            </xs:restriction>
        </xs:simpleType>

    </xs:element>

    <xs:element name="Return_Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label"/>
                <xs:element ref="Return"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Delivery">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Available" />
                <xs:enumeration value="Not Available" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Delivery_Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label"/>
                <xs:element ref="Delivery"/>
            </xs:sequence>
        </xs:complexType>

    </xs:element>

    <xs:element name="Personalized">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Can be personalized" />
                <xs:enumeration value="Cannot be personalized" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    
    <xs:element name="Personalized_Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label"/>
                <xs:element ref="Personalized"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CashBack">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Available" />
                <xs:enumeration value="Not Available" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Cashback_Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label"/>
                <xs:element ref="CashBack"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Discount" type="xs:float" />

    <xs:element name="Discount_Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label" />
                <xs:element ref="Discount" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Redeem">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Online" />
                <xs:enumeration value="In-Store" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Redeem_Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label" />
                <xs:element ref="Redeem" />
            </xs:sequence>
        </xs:complexType>

    </xs:element>

    <xs:element name="Users" type="xs:int" />

    <xs:element name="Number_Of_Users">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label" />
                <xs:element ref="Users" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="Card_Number" type="xs:int"/>

    <xs:element name="Card">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label" />
                <xs:element ref="Card_Number"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:attribute name="currency" default="USD">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="USD" />
                <xs:enumeration value="AUD" />
                <xs:enumeration value="GBP" />
                <xs:enumeration value="INR" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="Total" type="xs:float" />

    <xs:element name="Cost">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label" />
                <xs:element ref="Total" />
            </xs:sequence>
            <xs:attribute type="xs:string" name="currency" use="required" />
        </xs:complexType>
    </xs:element>


    <xs:attribute name="country" default="USA">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="USA" />
                <xs:enumeration value="Australia" />
                <xs:enumeration value="UK" />
                <xs:enumeration value="India" />
                <xs:enumeration value="Worldwide" />

            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="Validity_Date" type="xs:date" />

    <xs:element name="Validity">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label" />
                <xs:element ref="Validity_Date" />
            </xs:sequence>
            <xs:attribute ref="country" use="required" />
        </xs:complexType>
    </xs:element>


    <xs:attribute name="reload" default="Non-Reloadable">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Non-Reloadable" />
                <xs:enumeration value="Reloadable" />

            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>


    <xs:element name="Type_Name" type="xs:string" />
    <xs:element name="Type">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label" />
                <xs:element ref="Type_Name" />
            </xs:sequence>
            <xs:attribute ref="reload" use="optional" />
        </xs:complexType>
    </xs:element>


    <xs:attribute name="sector">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Technology" />
                <xs:enumeration value="Video Game" />
                <xs:enumeration value="Ecommerce" />
                <xs:enumeration value="Marketing" />
                <xs:enumeration value="Others" />

            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="Company_Name" type="xs:string" />
    <xs:element name="Company">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label" />
                <xs:element ref="Company_Name" />
            </xs:sequence>
            <xs:attribute ref="sector"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Product_Name" type="xs:string" />


    <xs:attribute name="type" default="Digital">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Physical" />
                <xs:enumeration value="Digital" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>


    <xs:element name="GiftCard_Details">
        <xs:complexType>
            <xs:all>
                <xs:element ref="Product_Name" />
                <xs:element ref="Company" />
                <xs:element ref="Type" />
                <xs:element ref="Validity" />
                <xs:element ref="Cost" />
                <xs:element ref="Card" />
                <xs:element ref="Number_Of_Users" />
                <xs:element ref="Redeem_Group"/>
                <xs:element ref="Discount_Group" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="Cashback_Group" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="Personalized_Group" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="Delivery_Group" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="Return_Group" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="Guide" />
                <xs:element ref="Terms_Condition" />
            </xs:all>
            <xs:attribute ref="type" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="Logo" type="xs:string" />

    <xs:attribute name="id" type="xs:ID"/>

    <xs:element name="GiftCard">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Logo" />
                <xs:element ref="GiftCard_Details" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
            <xs:attribute ref="id" use="required" />
        </xs:complexType>
    </xs:element>


    <xs:element name="GiftCards_G1">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="GiftCard" maxOccurs="unbounded" minOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="GiftCards_G2">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="GiftCard" maxOccurs="unbounded" minOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="GiftCards">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="GiftCards_G1" />
                <xs:element ref="GiftCards_G2" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="Website_Logo" type="xs:string" />
    <xs:element name="Website" type="xs:string" />


    <xs:element name="Website_Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Website_Logo" />
                <xs:element ref="Website" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="Address_Logo" type="xs:string" />

    <xs:attribute name="street" type="xs:string" fixed="Oxford Street"/>

    <xs:element name="Address">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute ref="street" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>

    </xs:element>

    <xs:element name="Address_Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Address_Logo" />
                <xs:element ref="Address" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Email_Logo" />

    <xs:element name="Email">
        <xs:simpleType>
            <xs:restriction base="xs:token">
                <xs:maxLength value="254"/>
                <xs:pattern value="[_\-a-zA-Z0-9\.\+]+@[a-zA-Z0-9](\.?[\-a-zA-Z0-9]*[a-zA-Z0-9])*"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Email_Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Email_Logo" />
                <xs:element ref="Email" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Phone_Logo"/>

    <xs:attribute name="phoneType"/>
    <xs:element name="Phone_Number">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:int">
              <xs:attribute ref="phoneType" use="optional"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>

    <xs:element name="Phone_Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Phone_Logo" />
                <xs:element ref="Phone_Number" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Store_Logo" />
    <xs:element name="Name" type="xs:string" />

    <xs:element name="Store_Details">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Store_Logo" />
                <xs:element ref="Name" />
                <xs:element ref="Phone_Group" />
                <xs:element ref="Email_Group" />
                <xs:element ref="Address_Group" />
                <xs:element ref="Website_Group" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="AboutImg" />

    <xs:attribute name="founder" type="xs:string" fixed="Jack Donalds" />
    <xs:attribute name="founded" type="xs:date" fixed="2021-09-24"/>

    <xs:element name="Store">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Store_Details" />
                <xs:element ref="AboutImg" />
            </xs:sequence>
            <xs:attribute ref="founder" use="required"/>
            <xs:attribute ref="founded" use="required"/>
        </xs:complexType>
    </xs:element>


    <xs:attribute name="slogan" type="xs:string" fixed="Gifts for all" />

    <xs:element name="GaloreGifts">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Home" />
                <xs:element ref="GiftCards" />
                <xs:element ref="Store" />
            </xs:sequence>
            <xs:attribute ref="slogan" use="required"/>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== TenzingT-Lama2001/GaloreGifts/catalog_20049082.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!-- css link -->
<?xml-stylesheet type="text/css" href="catalog_20049082.css"?>
<!-- schema link -->
<!-- <GaloreGifts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_20049082.xsd"> -->
<GaloreGifts slogan="Gifts for all" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="catalog_20049082.xsd">


    <Home>
        <!-- <Box class="box">

        </Box> -->
        <Nav>

            <Galore_Logo />
            <Nav_Menu>
                <Shop>Shop</Shop>
                <Pricing>Pricing</Pricing>
                <Blog>Blog</Blog>
                <Contact>Contact</Contact>
            </Nav_Menu>
            <ShopBtn>
                Shop now
            </ShopBtn>


        </Nav>
        <Body>
            <Description>
                <Title>Galore Gifts</Title>
                <Sub_Title>GIFTS FOR ALL</Sub_Title>
                <Info>
                      
                        We sell and deliver digital &amp; physical gift cards to your doorstep. Make sure to remember us.                  
                </Info>

                <CallToActionBtn>
                    Get your giftcard
                </CallToActionBtn>


            </Description>

            <Photo />


        </Body>

    </Home>

    <GiftCards>
        <GiftCards_G1>
            <GiftCard id='a1'>


                <Logo />


                <GiftCard_Details type='Digital'>
                    <Product_Name> Amazon Gift Card</Product_Name>
                    <Company sector="Ecommerce">
                        <label>Company:</label>
                        <Company_Name>
                            Amazon
                        </Company_Name>
                    </Company>
                    <Type reload="Non-Reloadable">
                        <label>Type:</label>
                        <Type_Name>
                            Digital
                        </Type_Name>
                    </Type>
                    <Validity country="USA">
                        <label>Validity: </label>
                        <Validity_Date>
                            2022-10-10
                        </Validity_Date>
                    </Validity>
                    <Cost currency="USD">
                        <label>Cost:$</label>
                        <Total>
                            45
                        </Total>
                    </Cost>
                    <Card>
                        <label>Card Number:</label>
                        <Card_Number>
                            10
                        </Card_Number>
                    </Card>
                    <Number_Of_Users>
                        <label>Number of users:</label>
                        <Users>
                            200000
                        </Users>
                    </Number_Of_Users>
                    <Discount_Group>
                        <label>Discount:$</label>
                        <Discount>5.00 </Discount>
                    </Discount_Group>
                    <Personalized_Group>
                        <label>Personalization:</label>
                        <Personalized>Can be personalized</Personalized>
                    </Personalized_Group>
                    <Redeem_Group>
                        <label>Redeemable:</label>
                        <Redeem>Online</Redeem>
                    </Redeem_Group>
                    <Guide>
                        <label>Guide:</label>
                        <Guideline>
                            Use the code sent to your phone to purchase something.
                        </Guideline>

                    </Guide>
                    <Terms_Condition>
                        For additional terms &amp; privacy policy visit www.amazon.com/giftcards
                    </Terms_Condition>
                </GiftCard_Details>

            </GiftCard>

            <GiftCard id='s1'>


                <Logo />

                <GiftCard_Details type='Digital'>
                    <Product_Name> Steam Gift Card</Product_Name>
                    <Company sector="Video Game">
                        <label>Company:</label>
                        <Company_Name>
                            Valve Corporation
                        </Company_Name>
                    </Company>
                    <Type reload="Reloadable">
                        <label>Type:</label>
                        <Type_Name>
                            Digital
                        </Type_Name>
                    </Type>
                    <Validity country="USA">
                        <label>Validity: </label>
                        <Validity_Date>
                            2022-11-10
                        </Validity_Date>
                    </Validity>
                    <Cost currency="USD">
                        <label>Cost:$</label>
                        <Total>
                            35
                        </Total>
                    </Cost>
                    <Card>
                        <label>Card Number:</label>
                        <Card_Number>
                            12
                        </Card_Number>
                    </Card>
                    <Number_Of_Users>
                        <label>Number of users:</label>
                        <Users>
                            10000
                        </Users>
                    </Number_Of_Users>
                    <Discount_Group>
                        <label>Discount:$</label>
                        <Discount>1.00</Discount>
                    </Discount_Group>
                    <Redeem_Group>
                        <label>Redeemable:</label>
                        <Redeem>Online</Redeem>
                    </Redeem_Group>
                    <Guide>
                        <label>Guide:</label>
                        <Guideline>
                            Use the code sent to your phone to purchase something.
                        </Guideline>

                    </Guide>
                    <Terms_Condition>
                        For additional terms &amp; privacy policy visit www.steam.com/giftcards
                    </Terms_Condition>
                </GiftCard_Details>


            </GiftCard>
            <GiftCard id='x1'>


                <Logo />


                <GiftCard_Details type='Digital'>
                    <Product_Name> XBOX Gift Card</Product_Name>
                    <Company sector="Technology">
                        <label>Company:</label>
                        <Company_Name>
                            Microsoft
                        </Company_Name>
                    </Company>
                    <Type reload="Reloadable">
                        <label>Type:</label>
                        <Type_Name>
                            Digital
                        </Type_Name>
                    </Type>
                    <Validity country="USA">
                        <label>Validity: </label>
                        <Validity_Date>
                            2022-10-10
                        </Validity_Date>
                    </Validity>
                    <Cost currency="GBP">
                        <label>Cost:Â£</label>
                        <Total>
                            25
                        </Total>
                    </Cost>
                    <Card>
                        <label>Card Number:</label>
                        <Card_Number>
                            13
                        </Card_Number>
                    </Card>
                    <Number_Of_Users>
                        <label>Number of users:</label>
                        <Users>
                            7000
                        </Users>
                    </Number_Of_Users>
                    <Redeem_Group>
                        <label>Redeemable:</label>
                        <Redeem>Online</Redeem>
                    </Redeem_Group>
                    <Guide>
                        <label>Guide:</label>
                        <Guideline>
                            Use the code sent to your phone to purchase something.
                        </Guideline>

                    </Guide>
                    <Terms_Condition>
                        For additional terms &amp; privacy policy visit  www.xbox.com/giftcards
                    </Terms_Condition>
                </GiftCard_Details>


            </GiftCard>


        </GiftCards_G1>


        <GiftCards_G2>
            <GiftCard id='play1'>


                <Logo />

                <GiftCard_Details type='Digital'>
                    <Product_Name> Playstore Gift Card</Product_Name>
                    <Company sector="Technology">
                        <label>Company:</label>
                        <Company_Name>
                            Google
                        </Company_Name>
                    </Company>
                    <Type reload="Non-Reloadable">
                        <label>Type:</label>
                        <Type_Name>
                            Digital
                        </Type_Name>
                    </Type>
                    <Validity country="USA">
                        <label>Validity: </label>
                        <Validity_Date>
                            2023-01-10
                        </Validity_Date>
                    </Validity>
                    <Cost currency="USD">
                        <label>Cost:$</label>
                        <Total>
                            35
                        </Total>
                    </Cost>
                    <Card>
                        <label>Card Number:</label>
                        <Card_Number>
                            20
                        </Card_Number>
